export function drivePickerPage(_req,res) {
  res.set('Cache-Control','no-store');
  res.set('Referrer-Policy','strict-origin');
  res.set('X-Content-Type-Options','nosniff');
  res.set('Content-Security-Policy',"default-src 'none'; script-src 'unsafe-inline' https://apis.google.com https://www.gstatic.com; style-src 'unsafe-inline'; img-src 'self' data: https://*.google.com https://*.gstatic.com; connect-src 'self' https://*.googleapis.com https://docs.google.com; frame-src https://docs.google.com; frame-ancestors 'none'; base-uri 'none'");
  res.type('html').send(`<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lilly archive folder</title><style>body{font:17px system-ui;max-width:740px;margin:48px auto;padding:0 20px;color:#17233b}button{padding:14px 20px;background:#1746a2;color:white;border:0;border-radius:8px;font:inherit;cursor:pointer}button:disabled{opacity:.5}p{line-height:1.5}</style></head><body><h1>Authorize Job Posting Archive</h1><p>Choose your existing <strong>Job Posting Archive</strong> folder in Google’s picker. This lets Lilly save job PDFs there using the Google account you connected.</p><button id="select" disabled>Select archive folder</button><p id="message" role="status">Loading Google’s folder picker…</p><p><a href="/auth-browser">Back to Lilly</a></p><script>
const button=document.getElementById('select'),message=document.getElementById('message');
function pickerLoaded(){gapi.load('picker',{callback:()=>{button.disabled=false;message.textContent='Ready to select your archive folder.'},onerror:()=>{message.textContent='Google’s picker could not load. Please reload and try again.'}})}
async function api(p,body){const r=await fetch('/auth-browser/drive/'+p,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'Unlock Lilly again, then return to this page.');return j}
button.onclick=async()=>{button.disabled=true;try{const c=await api('picker-config');const view=new google.picker.DocsView(google.picker.ViewId.FOLDERS).setIncludeFolders(true).setSelectFolderEnabled(true);const picker=new google.picker.PickerBuilder().addView(view).setOAuthToken(c.accessToken).setDeveloperKey(c.apiKey).setAppId(c.appId).setOrigin(location.origin).setTitle('Choose Job Posting Archive').setCallback(async(data)=>{if(data.action===google.picker.Action.CANCEL){button.disabled=false;message.textContent='No folder selected.';return}if(data.action!==google.picker.Action.PICKED)return;picker.dispose();const selected=data.docs?.[0]?.id;if(selected!==c.folderId){message.textContent='That is a different folder. Select the existing Job Posting Archive folder.';button.disabled=false;return}try{const result=await api('confirm-folder',{folderId:selected});message.textContent=result.archiveReady?'Archive folder authorized. Lilly is ready for the PDF test.':(result.reason||'Folder access is not ready yet. Try selecting it again.')}catch(e){message.textContent=e.message}button.disabled=false}).build();picker.setVisible(true);message.textContent='Select Job Posting Archive in Google’s picker.'}catch(e){message.textContent=e.message;button.disabled=false}};
</script><script async defer src="https://apis.google.com/js/api.js" onload="pickerLoaded()"></script></body></html>`);
}
